arquivos_gerados:
  geogrid: 0
  gfs: 0
  gfs_csv: 0
  metgrid: 0
  ungrib: 0
  wrfinput: 0
  wrfout: 0
  wrfout_csv: 0
  wrfrst: 0
cores: 6
data_final: '2026-06-30 00:00:00'
data_inicial: '2026-06-01 00:00:00'
data_mais_recente: '2026-06-05 00:00:00'
dom: 4
etapa: 0
geogrid_rodou: true
tamanho_arquivos:
  geogrid: 0
  gfs: 0
  gfs_csv: 0
  metgrid: 0
  ungrib: 0
  wrfinput: 0
  wrfout: 0
  wrfout_csv: 0
  wrfrst: 0
tempo_execucao:
  conversao_dados_gfs_para_csv: 0
  convertendo_dados_wrf_para_csv: 0
  extracao_dados_gfs: 0
  geogrid: 0
  metgrid: 0
  real: 0
  ungrib: 0
  wrf: 0
