arquivos_gerados:
  geogrid: 4
  gfs: 9
  gfs_csv: 1
  metgrid: 0
  ungrib: 9
  wrfinput: 0
  wrfout: 0
  wrfout_csv: 0
  wrfrst: 0
cores: 6
data_final: '2026-06-02'
data_inicial: '2026-06-01'
data_mais_recente: '2026-06-01'
etapa: 5
tamanho_arquivos:
  geogrid: 3032933
  gfs: 4824608937
  gfs_csv: 3104
  metgrid: 0
  ungrib: 7363609416
  wrfinput: 0
  wrfout: 0
  wrfout_csv: 0
  wrfrst: 0
tempo_execucao:
  conversao_dados_gfs_para_csv: 18.599869
  convertendo_dados_wrf_para_csv: 0
  extracao_dados_gfs: 121.714695
  geogrid: 6.269809
  metgrid: 0
  real: 0
  ungrib: 164.511646
  wrf: 0
